### ISSUE TITLE
No longer build with Cygwin 2.11.0 due to clearenv()

### ISSUE THREAD

**Issue by DDoSolitary** [dcreager/libcork#146]
Cygwin has implemented `clearenv()` since v2.11.0 so now compiler complains about multiple declaration.

```
Making all in libcork
make[2]: Entering directory '/home/appveyor/shadowsocks-libev/libcork'
  CC       src/libcork/cli/libcork_la-commands.lo
  CC       src/libcork/core/libcork_la-allocator.lo
  CC       src/libcork/core/libcork_la-error.lo
  CC       src/libcork/core/libcork_la-gc.lo
  CC       src/libcork/core/libcork_la-hash.lo
  CC       src/libcork/core/libcork_la-ip-address.lo
  CC       src/libcork/core/libcork_la-mempool.lo
  CC       src/libcork/core/libcork_la-timestamp.lo
  CC       src/libcork/core/libcork_la-u128.lo
  CC       src/libcork/ds/libcork_la-array.lo
  CC       src/libcork/ds/libcork_la-bitset.lo
  CC       src/libcork/ds/libcork_la-buffer.lo
  CC       src/libcork/ds/libcork_la-dllist.lo
  CC       src/libcork/ds/libcork_la-file-stream.lo
  CC       src/libcork/ds/libcork_la-hash-table.lo
  CC       src/libcork/ds/libcork_la-managed-buffer.lo
  CC       src/libcork/ds/libcork_la-ring-buffer.lo
  CC       src/libcork/ds/libcork_la-slice.lo
  CC       src/libcork/posix/libcork_la-directory-walker.lo
  CC       src/libcork/posix/libcork_la-env.lo
src/libcork/posix/env.c:194:1: error: conflicting types for ‘clearenv’
 clearenv(void)
 ^~~~~~~~
In file included from /usr/include/stdlib.h:26:0,
                 from src/libcork/posix/env.c:10:
/usr/include/cygwin/stdlib.h:30:5: note: previous declaration of ‘clearenv’ was here
 int clearenv (void);
     ^~~~~~~~
make[2]: *** [Makefile:723: src/libcork/posix/libcork_la-env.lo] Error 1
make[2]: Leaving directory '/home/appveyor/shadowsocks-libev/libcork'
```

http://cygwin.1069669.n5.nabble.com/PATCH-v2-0-6-Implement-clearenv-td141025.html
